/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-secondary": "#f2f1ff",
        "inverse-on-surface": "#9a9da0",
        "secondary-fixed-dim": "#b4c1ff",
        "on-tertiary-fixed-variant": "#6a1f76",
        "tertiary-fixed-dim": "#e48fec",
        "error-container": "#fb5151",
        "outline-variant": "#abadb0",
        "on-background": "#2c2f32",
        "surface-container": "#e5e8ec",
        "on-primary-container": "#00214f",
        "secondary-dim": "#2b47ab",
        "on-surface-variant": "#595c5e",
        "inverse-primary": "#4b8eff",
        "surface-container-highest": "#d9dde1",
        "on-tertiary-fixed": "#41004d",
        "on-tertiary-container": "#60136d",
        "primary-fixed-dim": "#5191ff",
        "on-primary": "#f0f2ff",
        "tertiary-container": "#f39cfb",
        "tertiary-fixed": "#f39cfb",
        "error": "#b31b25",
        "secondary": "#3853b7",
        "background": "#f5f7fa",
        "tertiary-dim": "#7a2f86",
        "surface-container-low": "#eef1f4",
        "surface-bright": "#f5f7fa",
        "on-primary-fixed": "#000000",
        "surface": "#f5f7fa",
        "outline": "#74777a",
        "surface-container-high": "#dfe3e7",
        "on-primary-fixed-variant": "#002a61",
        "on-error-container": "#570008",
        "primary-fixed": "#6c9fff",
        "surface-dim": "#d0d5d9",
        "on-tertiary": "#ffeefb",
        "secondary-fixed": "#c6cfff",
        "on-secondary-fixed-variant": "#2c48ac",
        "surface-variant": "#d9dde1",
        "primary": "#0058bb",
        "error-dim": "#9f0519",
        "on-error": "#ffefee",
        "on-surface": "#2c2f32",
        "on-secondary-container": "#203ea2",
        "tertiary": "#883c93",
        "secondary-container": "#c6cfff",
        "inverse-surface": "#0b0f11",
        "on-secondary-fixed": "#00288d",
        "surface-tint": "#0058bb",
        "primary-container": "#6c9fff",
        "primary-dim": "#004ca4",
        "surface-container-lowest": "#ffffff"
      },
      "borderRadius": {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      "fontFamily": {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "inter": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
